name: adv_eeg
version: 1.0.0+1
description: A new Flutter project.
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  animated_custom_dropdown: ^1.2.2
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.8.0
  firebase_messaging: ^14.3.0
  flutter:
    sdk: flutter
  flutter_bluetooth_seria_changed: ^0.4.0
  flutter_local_notifications: ^13.0.0
  flutter_progress_hud: ^2.0.2
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  http: ^0.13.5
  intl: ^0.18.0
  introduction_screen: ^3.0.2
  liquid_progress_indicator: ^0.4.0
  liquid_progress_indicator_ns: ^1.0.0
  modal_progress_hud_nsn: ^0.3.0
  multi_charts: ^0.3.0
  scoped_model: ^2.0.0-nullsafety.0
  sparkline: ^1.0.0
  step_progress_indicator: ^1.0.2
  string_contains: ^0.0.3
  syncfusion_flutter_charts: ^20.4.53
  toast: ^0.3.0
dependency_overrides:
  # Override for `flutter_local_notifications`:
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: true
  remove_alpha_ios: true
  ios: true
  image_path: assets/images/logo.png

flutter_native_splash:
  background_image: assets/images/splash.png

flutter_app_name:
  name: My Awesome App
