name: adv_eeg
version: 1.0.0+1
description: A new Flutter project.
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  firebase_core: ^2.8.0
  firebase_messaging: ^14.3.0
  flutter:
    sdk: flutter
  flutter_bluetooth_seria_changed: ^0.4.0
  flutter_inappwebview: ^5.7.2+3
  flutter_local_notifications: ^9.1.5
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^5.0.0
  http: ^1.0.0
  intl: ^0.18.1
  modal_progress_hud_nsn: ^0.3.0
  open_file: ^3.3.1
  pdf: ^3.10.4
  permission_handler: ^10.2.0
  step_progress_indicator: ^1.0.2
  string_contains: ^1.0.0
  syncfusion_flutter_charts: ^21.2.8
  syncfusion_flutter_core: ^21.2.8
  syncfusion_flutter_pdf: ^21.2.8
  toast: ^0.3.0
  url_launcher: ^6.1.11
  youtube_player_flutter: ^8.1.2
dependency_overrides:
  # Override for `flutter_local_notifications`:
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  change_app_package_name: ^1.1.0
  dependency_validator: ^3.2.2
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - shorebird.yaml

flutter_icons:
  android: true
  remove_alpha_ios: true
  ios: true
  image_path: assets/images/logo.png

flutter_native_splash:
  background_image: assets/images/splash.png

flutter_app_name:
  name: My Awesome App
