// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLFew1rGCvXKZBnENXAfH_duEwUnp3X0M',
    appId: '1:650062831167:web:70507348f7e5ad0fa4228a',
    messagingSenderId: '650062831167',
    projectId: 'push-notification-for-ad-98ed4',
    authDomain: 'push-notification-for-ad-98ed4.firebaseapp.com',
    storageBucket: 'push-notification-for-ad-98ed4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_AM4GKvGib5J2oL6SpzzbjeDn0u2cB64',
    appId: '1:650062831167:android:a0ff3bbea8c79388a4228a',
    messagingSenderId: '650062831167',
    projectId: 'push-notification-for-ad-98ed4',
    storageBucket: 'push-notification-for-ad-98ed4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSIClG2qIJU9XcWFLfpkPGdosA7F-IuHo',
    appId: '1:650062831167:ios:a7637b67fb233819a4228a',
    messagingSenderId: '650062831167',
    projectId: 'push-notification-for-ad-98ed4',
    storageBucket: 'push-notification-for-ad-98ed4.appspot.com',
    iosClientId: '650062831167-f21bkfevev4i411os6rv6un33trpgosj.apps.googleusercontent.com',
    iosBundleId: 'com.example.advEgg',
  );
}
